//@ui5-bundle projects/Component-preload.js
sap.ui.predefine("projects/Component", ["sap/ui/core/UIComponent","projects/model/models"],(e,t)=>{"use strict";return e.extend("projects.Component",{metadata:{manifest:"json",interfaces:["sap.ui.core.IAsyncContentCreation"]},init(){e.prototype.init.apply(this,arguments);this.setModel(t.createDeviceModel(),"device");this.getRouter().initialize()}})});
sap.ui.predefine("projects/controller/App.controller", ["sap/ui/core/mvc/Controller"],e=>{"use strict";return e.extend("projects.controller.App",{onInit(){}})});
sap.ui.predefine("projects/controller/Homepage.controller", ["sap/ui/core/mvc/Controller"],e=>{"use strict";return e.extend("projects.controller.Homepage",{onInit(){},onTest:function(){var e=1}})});
sap.ui.predefine("projects/model/models", ["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
sap.ui.require.preload({
	"projects/i18n/i18n.properties":'# This is the resource bundle for projects\n\n#Texts for manifest.json\n\n#XTIT: Application name\nappTitle=RCosta\n\n#YDES: Application description\nappDescription=\n#XTIT: Main view title\ntitle=RCosta App Resume\n\nhomepage.aboutme.title = About Me',
	"projects/manifest.json":'{"_version":"1.65.0","sap.app":{"id":"projects","type":"application","i18n":{"bundleUrl":"i18n/i18n.properties","supportedLocales":[""]},"applicationVersion":{"version":"0.0.1"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","sourceTemplate":{"id":"@sap/generator-fiori:basic","version":"1.16.3","toolsId":"58093012-eee7-4afb-a16b-147cd6254bc6"}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":false,"dependencies":{"minUI5Version":"1.132.1","libs":{"sap.m":{},"sap.ui.core":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"projects.i18n.i18n","supportedLocales":[""]}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","controlAggregation":"pages","controlId":"app","transition":"slide","type":"View","viewType":"XML","path":"projects.view","async":true,"viewPath":"projects.view"},"routes":[{"name":"RouteHomepage","pattern":":?query:","target":["TargetHomepage"]}],"targets":{"TargetHomepage":{"id":"Homepage","name":"Homepage"}}},"rootView":{"viewName":"projects.view.App","type":"XML","id":"App"}}}',
	"projects/view/App.view.xml":'<mvc:View controllerName="projects.controller.App"\n    displayBlock="true"\n    xmlns:mvc="sap.ui.core.mvc"\n    xmlns="sap.m"><App id="app"></App></mvc:View>',
	"projects/view/Homepage.view.xml":'<mvc:View controllerName="projects.controller.Homepage"\n          xmlns:mvc="sap.ui.core.mvc"\n          xmlns="sap.m"\n          xmlns:core="sap.ui.core"\n          xmlns:l="sap.ui.layout"><Page id="page"\n          title="{i18n>title}"\n          showHeader="false"\n          class="myBackgroundImage"><content><VBox><OverflowToolbar class="headerColor headerSize"\n                                 height="60px"><core:Icon src="sap-icon://sap-ui5"\n                               size="30px" /><Title text="{i18n>title}"\n                           level="H1"\n                           class="headerTextColor headerTextSize" /><ToolbarSpacer /></OverflowToolbar></VBox><l:Grid><FlexBox><layoutData><l:GridData span="XL3 L3 M2 S1" /></layoutData></FlexBox><Panel class="sapUiLargeMarginTop"><VBox><Title text="{i18n>homepage.aboutme.title}" /></VBox><layoutData><l:GridData span="XL6 L6 M8 S10" /></layoutData></Panel><FlexBox><layoutData><l:GridData span="XL4 L3 M2 S1" /></layoutData></FlexBox></l:Grid><VBox class="sapUiLargeMarginTop"\n                  alignContent="Center"\n                  visible="{= !${device>/system/phone} }"><HBox justifyContent="SpaceBetween"\n                      class="myCenterMargins"><Button text="Teste"\n                            width="100px" /><Button text="Teste"\n                            width="100px" /><Button text="Teste"\n                            width="100px" /></HBox></VBox><VBox class="sapUiLargeMarginTop"\n                  alignContent="Center"\n                  visible="{device>/system/phone}"><Button text="Teste"\n                        width="100px"\n                        press="onTest" /><Button text="Teste"\n                        width="100px" /><Button text="Teste"\n                        width="100px" /></VBox></content></Page></mvc:View>'
});
//# sourceMappingURL=Component-preload.js.map
